version: '3'

services:
  web:
    build: .
      #context: .
      #dockerfile: Dockerfile
    command: python /code/manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    volumes:
      - .:/code
    depends_on:
      - db
    links:
      - db:db

      
  db:
     image: 'postgres'
     volumes:
      - postgres_data:/var/lib/postgresql/data
     ports:
       - '5432'
     environment:
            - POSTGRES_DB=booksdb
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres

volumes :
  postgres_data:

